name: Run the down alerts

on:
  push:
    branches:
      - main

jobs:
  run-api:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: docker build -t pjgame841/downalerts-api .
      - name: Stop old containers
        run: docker rm $(docker stop $(docker ps -a -q --filter name=pj_downalerts-api --format="{{.ID}}"))
        continue-on-error: true

      - name: Remove old image
        run: docker rmi -f $(docker images -f "dangling=true" -q)
        continue-on-error: true

      - name: Start
        env:
          DISCORD_WEBHOOK: "${{ secrets.DISCORD_WEBHOOK }}"
        run: docker run -d -e DISCORD_WEBHOOK=$DISCORD_WEBHOOK -p 5000:5000 --add-host=host.docker.internal:host-gateway --name=pj_downalerts-api pjgame841/downalerts-api

  run-client:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: docker build -t pjgame841/downalerts-web ./client
      - name: Stop old containers
        run: docker rm $(docker stop $(docker ps -a -q --filter name=pj_downalerts-web --format="{{.ID}}"))
        continue-on-error: true

      - name: Remove old image
        run: docker rmi -f $(docker images -f "dangling=true" -q)
        continue-on-error: true

      - name: Start
        run: docker run -d -p 3000:3000 --add-host=host.docker.internal:host-gateway --name=pj_downalerts-web pjgame841/downalerts-web
