name: Run the down alerts

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: docker build -t pjgame841/downalerts .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker push
        run: docker push pjgame841/portfolio

      - name: Stop old containers
        run: docker rm $(docker stop $(docker ps -a -q --filter name=pj_downalerts --format="{{.ID}}"))
        continue-on-error: true

      - name: Remove old image
        run: docker rmi -f $(docker images -f "dangling=true" -q)
        continue-on-error: true

      - name: Start
        env:
          DISCORD_WEBHOOK: "${{ secrets.DISCORD_WEBHOOK }}"
        run: docker run -d -e DISCORD_WEBHOOK=$DISCORD_WEBHOOK --name=pj_downalerts pjgame841/downalerts
